[project]
name = "simulation-foundry-python"
version = "0.1.0"
description = "Simulation Foundry Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.2.0",
    "ipympl>=0.10.0",
    "matplotlib>=3.10.8",
    "pandas>=3.0.1",
    "pre-commit>=4.5.1",
]
